import pandas as pd
from .utils import setup_logging

logger = setup_logging("risk")


def apply_risk_management(
    df: pd.DataFrame,
    capital: float = 100000.0,
    risk_per_trade: float = 0.01,
    transaction_cost_bps: float = 1.0,
    slippage_bps: float = 2.0,
) -> pd.DataFrame:
    """
    Apply position sizing and risk management based on volatility.
    Uses vectorized operations for geometric compounding.

    Args:
        df (pd.DataFrame): Data with 'Position', 'Volatility', 'Return'.
        capital (float): Initial starting capital.
        risk_per_trade (float): Fraction of capital to risk per trade (e.g., 0.01).

    Returns:
        pd.DataFrame: Data with 'Capital', 'Position_Size', 'PnL'.
    """
    df = df.copy()

    # Calculate leverage factor to target risk
    # Position Size (Units) = (Capital * Risk%) / Volatility
    # But here we model Capital growth.
    # Return contribution = Position * (Risk / Volatility) * Return

    # We delay Position and Volatility by 1 to match real trading (decision made at t-1)
    # The dataframe likely has aligned dates, but let's check input logic.
    # Strategy.py: df["Position"] = df["Signal"].replace(0, pd.NA).ffill()
    # This position is what we hold AT that time.
    # If we hold at time T, we get return of T+1? 
    # Usually Close-to-Close return at T is (Close_T - Close_T-1)/Close_T-1.
    # If we hold position from T-1 to T, we get Return_T.
    # So Position at T-1 determines PnL at T.

    # Shift position and volatility to align with returns they generate
    # The 'Return' column is Returns at T. generated by decision at T-1.

    pos_lag = df["Position"].shift(1).fillna(0)
    vol_lag = df["Volatility"].shift(1).ffill().fillna(0.01)  # Default to avoid div/0

    # Avoid infinite leverage
    leverage = (risk_per_trade / (vol_lag + 1e-6)).clip(0, 5)  # Cap leverage at 5x

    gross_strategy_return = pos_lag * leverage * df["Return"].fillna(0)

    # Cost model: charge bps on directional turnover. A flip (+1 -> -1) costs 2x.
    turnover = (pos_lag - pos_lag.shift(1).fillna(0)).abs()
    per_turnover_cost = (transaction_cost_bps + slippage_bps) / 10000.0
    trading_cost = turnover * per_turnover_cost
    strategy_return = gross_strategy_return - trading_cost

    # Calculate Capital path
    # (1 + r1) * (1 + r2) ...
    df["Gross_Strategy_Return"] = gross_strategy_return
    df["Trading_Cost"] = trading_cost
    df["Turnover"] = turnover
    df["Strategy_Return"] = strategy_return
    df["Capital"] = capital * (1 + df["Strategy_Return"]).cumprod()

    # Calculate PnL and Size for reference (back-calculated from Capital)
    # Note: This is an approximation of the loop version's reporting,
    # but the Capital curve is the source of truth.
    df["PnL"] = df["Capital"].diff().fillna(0)

    # Reconstruct Position Size (Units) for checking
    # Size = Capital(t-1) * Risk / Vol(t-1)
    # We can approximate for display
    prev_cap = df["Capital"].shift(1).fillna(capital)
    df["Position_Size"] = (prev_cap * risk_per_trade) / (vol_lag + 1e-6) * pos_lag.abs()

    logger.info(f"Risk management applied. Final Capital: {df['Capital'].iloc[-1]:.2f}")
    return df
